### ISSUE TITLE
Functions 2.0 Language Extensibility Meta Issue

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1964]
**Overview**

Providing language extensibility via a protobuf / grpc service contract. The script host runs a grpc server and starts language worker processes (serving as grpc clients) that connect back to the server.

These language workers are currently consumed in the host via nuget package, though we'd like to split them out from the deployment.

The language workers (node & java) currently depend on the runtime existing on the platform - we don't bring node or java with the worker, but search for it in the environment based on configuration.

**Work Items:**

- [ ] Add doccomments for public interfaces
- [ ] Script Abstractions Project & Nuget (#1800)
- [ ] Language Worker Nuget Extensibility (#1871)
- [ ] Grpc Worker Test Suite (#1768)
- [ ] Improve Test Coverage (#1766)
- [ ] Generic stream support for OOP languages (#1814)
- [ ] Node - provide access to raw request body (#1951)
- [ ] remove function.json metadata from load requests ($1836)

**Language Worker Repositories:**

- https://github.com/Azure/azure-functions-nodejs-worker
- https://github.com/Azure/azure-functions-java-worker
